language: java
script: mvn clean package
deploy:
  on:
    branch: master
  provider: heroku
  api_key:
    secure: "TGqlUEY/UfBguk/Um7Q68a1V+mWenVrLK4cF8ylkhTn5bKQnjmfeRiZru4Z/AVPyCSrrgQXWY158GiqJH3uod2B4ih+MlwbHP06cNS7OIoYVc1u8oCZwXqDw0QG/xLwa/n99c6XELtJrhv5yhjQ6FVh8tonfKOMJB+wXLNv6bv1CvyaKjyMUyoooJ7qsxAvh7ueC3QBiUWZ9FCpD5KWQsAoy4N+w3oWar2gZcdLKFzxxS6NPHAylOHpKU/oBcrl85TIKhdpuiywYYMBY8EyDGdfvyu5c8WS3142aW4rOf2svoNdAqHPFXoSrC6WE9Kn++j4o49f3HvIgmZUK6Cd1KlNXjfGoQ31ScDITBpuOoYopJuPkD6JGC+xPcDPXOO5fMJ+huw2pPYlunbqOtdRDbmqg6MtmQabyRclQL26YSRAg8LUTMhxD3lAyvfp9Ur4K6E8N/p5hYCxZwsdsEeK5Pw5U39M0RvbMqAzWOwYKlN9Ef5HKuJF7IPZh4deXkxS/bw7QxxwiAzb5rtVpYHRZTe5UOvMcbRI0ZjXAyU27Hbg4leIChgMinDms2SYclmPBWPKKTig1M3MeaEhuSbNg9XGqvg9crvGnFD45Z/PbCdAEpwLX6KQkpuDgyyoutnkuSAhxq1nnJbfDWhywK1l42vaJSlfhd4UFoAVSDorB7/Q="